name: Compatibility

on:
  push:
  pull_request:

jobs:
  minimum-supported-toolchains:
    name: Rust ${{ matrix.rust }} / Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: ['1.85']
        node: ['22']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: npm ci
      - run: npm test
      - run: npm run lint
